<?php

function getStr($string, $first, $second){
   return explode($second, explode($first, $string)[1])[0];
}

function inStr($s, $as){
   $s = strtoupper($s);
   if(!is_array($as)) $as=array($as);
   for($i=0;$i<count($as);$i++) if(strpos(($s),strtoupper($as[$i]))!==false) return true;
   return false;
}

function SEARCH($engine, $search){
   if($engine == "BING"){
      $ch = curl_init();

      curl_setopt($ch, CURLOPT_URL, 'https://www.bing.com/search?q='.urlencode($search));
      curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
      curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

      curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

      $headers = array();
      $headers[] = 'Authority: www.bing.com';
      $headers[] = 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9';
      $headers[] = 'Accept-Language: en-US,en;q=0.9';
      $headers[] = 'Cookie: SUID=M; MUID=3F46012DE14A6BEA13B110E2E01C6A64; _EDGE_V=1; MUIDB=3F46012DE14A6BEA13B110E2E01C6A64; SRCHD=AF=NOFORM; SRCHUID=V=2&GUID=5000C71BBC7E414B849E89CFC5E48E90&dmnchg=1; _SS=SID=31AE29F40B5664EE1469383B0A00653D; _UR=QS=0&TQS=0; _HPVN=CS=eyJQbiI6eyJDbiI6MSwiU3QiOjAsIlFzIjowLCJQcm9kIjoiUCJ9LCJTYyI6eyJDbiI6MSwiU3QiOjAsIlFzIjowLCJQcm9kIjoiSCJ9LCJReiI6eyJDbiI6MSwiU3QiOjAsIlFzIjowLCJQcm9kIjoiVCJ9LCJBcCI6dHJ1ZSwiTXV0ZSI6dHJ1ZSwiTGFkIjoiMjAyMi0wNi0yNlQwMDowMDowMFoiLCJJb3RkIjowLCJHd2IiOjAsIkRmdCI6bnVsbCwiTXZzIjowLCJGbHQiOjAsIkltcCI6Mn0=; ipv6=hit=1656253048265&t=4; MicrosoftApplicationsTelemetryDeviceId=be2edb5f-7a53-43e6-b3ee-ad002d53a017; _EDGE_S=F=1&SID=31AE29F40B5664EE1469383B0A00653D&mkt=en-id; ai_session=iktobySRTBsA5m/TPT3/Wy|1656249449418|1656249449418; SRCHUSR=DOB=20220626&T=1656249447000&TPC=1656249462000; dsc=order=News; SRCHHPGUSR=SRCHLANG=en&BRW=S&BRH=M&CW=1109&CH=961&SW=1920&SH=1080&DPR=1&UTC=480&DM=1&PV=15.0.0&HV=1656249463&WTS=63791846261';
      $headers[] = 'Referer: https://www.bing.com/search?q=%5BQUERRY%5D&form=QBLH&sp=-1&pq=%5Bquerry%5D&sc=2-8&qs=n&sk=&cvid=507602B458E7434FABCE6F65B186D5DD&ghsh=0&ghacc=0';
      $headers[] = 'Sec-Ch-Ua: \" Not A;Brand\";v=\"99\", \"Chromium\";v=\"102\", \"Google Chrome\";v=\"102\"';
      $headers[] = 'Sec-Ch-Ua-Arch: \"x86\"';
      $headers[] = 'Sec-Ch-Ua-Bitness: \"64\"';
      $headers[] = 'Sec-Ch-Ua-Full-Version: \"102.0.5005.115\"';
      $headers[] = 'Sec-Ch-Ua-Mobile: ?0';
      $headers[] = 'Sec-Ch-Ua-Model: \"\"';
      $headers[] = 'Sec-Ch-Ua-Platform: \"Windows\"';
      $headers[] = 'Sec-Ch-Ua-Platform-Version: \"15.0.0\"';
      $headers[] = 'Sec-Fetch-Dest: document';
      $headers[] = 'Sec-Fetch-Mode: navigate';
      $headers[] = 'Sec-Fetch-Site: same-origin';
      $headers[] = 'Sec-Fetch-User: ?1';
      $headers[] = 'Upgrade-Insecure-Requests: 1';
      $headers[] = 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36';
      curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

      $result = curl_exec($ch);
      if (curl_errno($ch)) {
         echo 'Error:' . curl_error($ch);
      }
      curl_close($ch);
      
      // die($result);
      // $input = 'startstring kasjdkajd endstring';
      preg_match_all('/(?<=<a href=")(.*?)(?=")/', $result, $matches);

      $urls = [];
      foreach($matches[1] as $url){
         if(filter_var($url, FILTER_VALIDATE_URL)){
            array_push($urls, $url);
         }
      }
      // var_dump($urls);
      if(count($urls) > 0){
         GET_LYRICS("KAPANLAGI", $urls[0]);
      }else{
         die(json_encode([
            "error" => 1,
            "msg" => "Lyrics not found",
         ]));
      }
   }
}

function GET_LYRICS($site, $url){
   if($site == "KAPANLAGI"){
         // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
         $ch = curl_init();

         curl_setopt($ch, CURLOPT_URL, $url);
         curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
         curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

         curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

         $headers = array();
         $headers[] = 'Authority: lirik.kapanlagi.com';
         $headers[] = 'Cache-Control: max-age=0';
         $headers[] = 'Sec-Ch-Ua: \" Not;A Brand\";v=\"99\", \"Google Chrome\";v=\"97\", \"Chromium\";v=\"97\"';
         $headers[] = 'Sec-Ch-Ua-Mobile: ?0';
         $headers[] = 'Sec-Ch-Ua-Platform: \"Windows\"';
         $headers[] = 'Upgrade-Insecure-Requests: 1';
         $headers[] = 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36';
         $headers[] = 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9';
         $headers[] = 'Sec-Fetch-Site: cross-site';
         $headers[] = 'Sec-Fetch-Mode: navigate';
         $headers[] = 'Sec-Fetch-User: ?1';
         $headers[] = 'Sec-Fetch-Dest: document';
         $headers[] = 'Referer: https://www.google.com/';
         $headers[] = 'Accept-Language: en-US,en;q=0.9';
         $headers[] = 'Cookie: klnShareSocmed=count%3D122%3Bsocial_sentence%3D122%20people%20like%20this.%3Burl%3Dhttps%3A%2F%2Flirik.kapanlagi.com%2Fartis%2Facha-septriasa%2Fsampai-menutup-mata%2F%3B; cookieEnabled=true; sawAd=true; _ga=GA1.2.856378882.1641574690; _gid=GA1.2.444352447.1641574690; __auc=575841e217e3579ecc5357c737e; _ga=GA1.3.856378882.1641574690; _gid=GA1.3.444352447.1641574690; liputan6_id_visitor_id=49b505ba-2888-4058-a443-ef3544550155; liputan6_id_gender=; cookieEnabled=true; sawAd=true; __asc=347b1c3a17e3f05293485bf1d2d; visitor_fp_id=a3ca4fb5472865ac434eadc7f01fd982; PHPSESSID=16a78f2325dc4b954e013a097bff8d9c; cto_bundle=ih79vl91d2hMUndVanUlMkJ3Z0NMMnBGVlBNbkhCU2hwT3ZRR3FXcHJQZUZzaGklMkI2ekolMkY5VXBITVBYNlM0S0hFRmRhTDJCV3M4c1NpaiUyQklIWHFVVmMlMkZmaGp3TWphUXBMbThQR2NjZ0dINndmWDFRTjZvV0JXUkNUeFFMb1puWWRkWHVQelM3VERmekpHUlEwTHN6N3h0NWs5R21BJTNEJTNE; _gali=v5-container';
         curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

         $result = curl_exec($ch);
         if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
         }
         curl_close($ch);
         preg_match_all('/(?<=class="lirik_line">)(.*?)(?=<\/span>)/', $result, $matches);

         array_pop($matches[0]);

         $lirik = $matches[0];
         $spaces = 0;
         // var_dump($matches[0]);
         for($i=1; $i<=count($matches[0]); $i++){
            if(inStr(getStr($result, 'line_'.strval($i), 'line_'.strval($i+1)), '<br')){
               array_splice( $lirik, $i + $spaces, 0, array(''));
               $spaces++;
            }
         }

         // var_dump($lirik);
         die(json_encode([
            "error" => 0,
            "msg" => "found",
            "lyrics" => $lirik
         ]));
   }
}

$title = isset($_GET['title']) ? $_GET['title'] : "Indah Cintaku";

SEARCH("BING", "site:lirik.kapanlagi.com ". $title);

?>